#!/bin/bash
DIR="$1"
: ${DIR:=/data}

if [ -d "$DIR" ]; then
  echo "Folder $DIR already existed!"
else
  echo "Creating folder $DIR..."
  mkdir -p $DIR
fi

SECRET="$2"
: ${SECRET:=`btsync --generate-secret`}

echo "Starting btsync to share $DIR using $SECRET as secret."

echo "{
    \"device_name\": \"Sync Server ($DIR)\",
    \"listening_port\": 55555,
    \"storage_path\": \"/btsync/.sync\",
    \"pid_file\": \"/var/run/btsync/btsync.pid\",
    \"check_for_updates\": false,
    \"use_upnp\": false,
    \"download_limit\": 0,
    \"upload_limit\": 0,
    \"shared_folders\": [
        {
            \"secret\": \"$SECRET\",
            \"dir\": \"$DIR\",
            \"use_relay_server\": true,
            \"use_tracker\": true,
            \"use_dht\": false,
            \"search_lan\": true,
            \"use_sync_trash\": false
        }
    ]
}" > /btsync/btsync.conf

btsync --config /btsync/btsync.conf --nodaemon
